### ISSUE TITLE
Store RemoteKey relations

### ISSUE THREAD

**Issue by Bloemkoolsaus** [neat-php/object#9]
The many relation -> set($remote) method does not remove items that are not in the new set.

**Comment by baukevdw** [comment]
The `Many->set($remotes)` method works as expected as do the store methods of the JunctionTable and the RemoteKey reference which can be used in combination with the Many relation.

Could you supply an example that illustrates the bug?

**Comment by annavanbiemen** [comment]
The cause is most likely in the store implementation of the [RemoteKey](../blob/master/classes/Relations/Reference/RemoteKey.php) reference. The comparision function currently returns boolean values, but 
should return integer (-1, 0, or 1) values instead.
